# Generated by Django 4.1 on 2024-03-31 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_alter_dish_options_alter_dish_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.dishtype'),
        ),
    ]
